### ISSUE TITLE
Disparition couche panoramax en cas de pb réseau

### ISSUE THREAD

**Issue by zorglubu** [u4y0u/panoramax-tools#1]
Je suis parti de chez moi ce matin avec toutes les infos affichées dans QField, mais au bout d'un moment, toutes les infos panoramax ont disparu, et QField indique "Tile request max retry error..."

Retour chez moi (wifi) tout est OK.
J'ai reproduit le pb chez moi en me mettant en mode avion. Et l'affichage panoramax revient dès que je remet le réseau wifi.

Question : est-il possible d'afficher les tuiles autour de moi puis de forcer QField à se mettre "hors ligne", sans chercher des MAJ ?

Merci.

**Comment by u4y0u** [comment]
Le seul moyen pour afficher des tuiles hors ligne est de les enregistrer avant départ mission dans le smartphone. QFiled n'est pas conçu pour utiliser autre chose que les données du projet et/ou des fonds cartographique en ligne.

L'opération est donc beaucoup plus complexe puisqu'elle necessite une préparation, puis un transfert de fichiers vers le mobile au minimum pour mettre les données de fond cartographique dans le répertoire du projet puisqu'il n'y aura pas moyen de les obtenir autrement.
L'utilisation devient de plus impossible si l'on sort du cadre de la zone prévue puisque les tuiles n'auront pas été chargées au préalable.

Ce n'est pas le but dans ces projets. J'ai bien précisé qu'il faut une connexion internet (en ligne).

Il existe des possibilités de travailler off line. Mais comme celle ci necessite le téléchargement des tuiles en préparation de mission, la solution est différente pour chaque utilisateur puisque qu'il y aura des vues et des niveaux de zoom  différents pour chacuns.

Autre problème si il y a plusieurs personnes qui couvrent la même zone. il sera impossible de voir les ajouts éffectués entre le départ de la mission et le retour en ligne et on peut se retrouver à 'doublonner' une zone pour rien.

Pour te donner une idée, voici un exemple d'utilisation off line avec synchro pc/smartphone et le plugin QField. (en anglais)

https://www.youtube.com/watch?v=_gTAdXCWnIg

**Comment by u4y0u** [comment]
Peut être voir avec les dev QField si il y a la possibilité de charger des tuiles dans un répertoire local dans une version future en sachant bien que ce ne sera valable qu'a l'instant T avant la deconnexion.

**Comment by zorglubu** [comment]
Merci pour ta réponse. Pourtant je suis en banlieue parisienne avec un réseau putôt correct.
Je vais retenter, il s'agissait peut-être d'un problème temporaire.
